services:
  users:
    image: users
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_NAME: testdb
      DB_USER: sa
      SPRING_PROFILES_ACTIVE: development
      APPLICATION_PORT: 80
    ports:
      - "8081:80"